<?php
/**
 * @author    JaJuMa GmbH <info@jajuma.de>
 * @copyright Copyright (c) 2022-present JaJuMa GmbH <https://www.jajuma.de>. All rights reserved.
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 */

declare(strict_types=1);

namespace Jajuma\AwesomeHyva\ViewModel;

use Hyva\Theme\ViewModel\SvgIcons;

/**
 * This class exists to offer autocompletion, it could have been a virtual type otherwise
 *
 * @method string addressBookHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string addressCardHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string angryHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string arrowAltCircleDownHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string arrowAltCircleLeftHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string arrowAltCircleRightHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string arrowAltCircleUpHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string bellSlashHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string bellHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string bookmarkHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string buildingHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string calendarAltHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string calendarCheckHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string calendarMinusHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string calendarPlusHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string calendarTimesHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string calendarHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string caretSquareDownHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string caretSquareLeftHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string caretSquareRightHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string caretSquareUpHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string chartBarHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string checkCircleHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string checkSquareHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string circleHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string clipboardHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string clockHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string cloneHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string closedCaptioningHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string commentAltHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string commentDotsHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string commentHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string commentsHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string compassHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string copyHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string copyrightHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string creditCardHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string dizzyHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string dotCircleHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string editHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string envelopeOpenHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string envelopeHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string eyeSlashHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string eyeHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string fileAltHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string fileArchiveHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string fileAudioHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string fileCodeHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string fileExcelHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string fileImageHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string filePdfHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string filePowerpointHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string fileVideoHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string fileWordHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string fileHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string flagHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string flushedHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string folderOpenHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string folderHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string fontAwesomeLogoFullHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string frownOpenHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string frownHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string futbolHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string gemHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string grimaceHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string grinAltHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string grinBeamSweatHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string grinBeamHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string grinHeartsHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string grinSquintTearsHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string grinSquintHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string grinStarsHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string grinTearsHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string grinTongueSquintHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string grinTongueWinkHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string grinTongueHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string grinWinkHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string grinHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string handLizardHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string handPaperHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string handPeaceHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string handPointDownHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string handPointLeftHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string handPointRightHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string handPointUpHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string handPointerHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string handRockHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string handScissorsHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string handSpockHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string handshakeHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string hddHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string heartHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string hospitalHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string hourglassHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string idBadgeHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string idCardHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string imageHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string imagesHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string keyboardHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string kissBeamHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string kissWinkHeartHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string kissHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string laughBeamHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string laughSquintHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string laughWinkHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string laughHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string lemonHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string lifeRingHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string lightbulbHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string listAltHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string mapHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string mehBlankHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string mehRollingEyesHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string mehHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string minusSquareHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string moneyBillAltHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string moonHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string newspaperHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string objectGroupHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string objectUngroupHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string paperPlaneHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string pauseCircleHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string playCircleHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string plusSquareHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string questionCircleHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string registeredHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string sadCryHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string sadTearHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string saveHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string shareSquareHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string smileBeamHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string smileWinkHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string smileHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string snowflakeHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string squareHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string starHalfHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string starHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string stickyNoteHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string stopCircleHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string sunHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string surpriseHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string thumbsDownHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string thumbsUpHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string timesCircleHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string tiredHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string trashAltHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string userCircleHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string userHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string windowCloseHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string windowMaximizeHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string windowMinimizeHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string windowRestoreHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 */

class AwesomeiconsRegular extends SvgIcons
{

}
