<?php
/**
 * @author    JaJuMa GmbH <info@jajuma.de>
 * @copyright Copyright (c) 2022-present JaJuMa GmbH <https://www.jajuma.de>. All rights reserved.
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 */

declare(strict_types=1);

namespace Jajuma\AwesomeHyva\ViewModel;

use Hyva\Theme\ViewModel\SvgIcons;

/**
 * This class exists to offer autocompletion, it could have been a virtual type otherwise
 *
 * @method string addressBookHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string addressCardHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string bellSlashHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string bellHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string bookmarkHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string buildingHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string calendarCheckHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string calendarDaysHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string calendarMinusHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string calendarPlusHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string calendarXmarkHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string calendarHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string chartBarHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string chessBishopHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string chessKingHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string chessKnightHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string chessPawnHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string chessQueenHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string chessRookHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string circleCheckHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string circleDotHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string circleDownHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string circleLeftHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string circlePauseHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string circlePlayHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string circleQuestionHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string circleRightHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string circleStopHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string circleUpHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string circleUserHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string circleXmarkHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string circleHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string clipboardHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string clockHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string cloneHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string closedCaptioningHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string commentDotsHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string commentHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string commentsHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string compassHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string copyHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string copyrightHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string creditCardHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string envelopeOpenHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string envelopeHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string eyeSlashHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string eyeHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceAngryHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceDizzyHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceFlushedHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceFrownOpenHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceFrownHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceGrimaceHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceGrinBeamSweatHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceGrinBeamHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceGrinHeartsHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceGrinSquintTearsHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceGrinSquintHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceGrinStarsHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceGrinTearsHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceGrinTongueSquintHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceGrinTongueWinkHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceGrinTongueHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceGrinWideHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceGrinWinkHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceGrinHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceKissBeamHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceKissWinkHeartHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceKissHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceLaughBeamHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceLaughSquintHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceLaughWinkHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceLaughHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceMehBlankHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceMehHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceRollingEyesHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceSadCryHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceSadTearHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceSmileBeamHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceSmileWinkHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceSmileHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceSurpriseHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string faceTiredHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string fileAudioHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string fileCodeHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string fileExcelHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string fileImageHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string fileLinesHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string filePdfHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string filePowerpointHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string fileVideoHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string fileWordHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string fileZipperHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string fileHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string flagHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string floppyDiskHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string folderClosedHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string folderOpenHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string folderHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string fontAwesomeHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string futbolHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string gemHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string handBackFistHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string handLizardHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string handPeaceHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string handPointDownHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string handPointLeftHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string handPointRightHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string handPointUpHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string handPointerHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string handScissorsHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string handSpockHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string handHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string handshakeHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string hardDriveHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string heartHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string hospitalHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string hourglassHalfHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string hourglassHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string idBadgeHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string idCardHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string imageHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string imagesHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string keyboardHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string lemonHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string lifeRingHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string lightbulbHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string mapHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string messageHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string moneyBill1Html(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string moonHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string newspaperHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string noteStickyHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string objectGroupHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string objectUngroupHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string paperPlaneHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string pasteHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string penToSquareHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string rectangleListHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string rectangleXmarkHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string registeredHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string shareFromSquareHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string snowflakeHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string squareCaretDownHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string squareCaretLeftHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string squareCaretRightHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string squareCaretUpHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string squareCheckHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string squareFullHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string squareMinusHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string squarePlusHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string squareHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string starHalfStrokeHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string starHalfHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string starHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string sunHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string thumbsDownHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string thumbsUpHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string trashCanHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string userHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string windowMaximizeHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string windowMinimizeHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 * @method string windowRestoreHtml(string $classnames = '', ?int $width = 24, ?int $height = 24, array $attributes = [])
 */

class Awesomeicons6Regular extends SvgIcons
{

}
